name: "Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          # Ensure Nix is installed in multi-user mode
          nix_path: nixpkgs=channel:nixpkgs-unstable
          install_url: https://nixos.org/nix/install

      - uses: cachix/cachix-action@v14
        with:
          name: devenv

      # Diagnostic Steps
      - name: List Installed Packages
        run: poetry run pip list

      - name: Print sys.path
        run: poetry run python -c "import sys; print(sys.path)"

      - name: Print Current Working Directory
        run: pwd

      - name: List Directory Contents
        run: ls -la

      - name: Find numpy in Site-Packages
        run: find $(python -c "import site; print(site.getsitepackages()[0])") -name "numpy*"

      - name: Print numpy Location
        run: poetry run python -c "import numpy; print(numpy.__file__)"

      - name: Run Tests
        run: poetry run pytest

      - name: Install devenv
        run: nix profile install nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
